image: node:latest

variables:
  SCOPE: MY-SCOPE

stages:
  - build
  - test
  - publish

build:
  stage: build
  artifacts:
    paths:
      - dist
  cache:
    key: $CI_COMMIT_REF_NAME
    policy: push
    paths:
      - node_modules
  script:
    - yarn
    - yarn build

test:
  stage: test
  cache:
    key: $CI_COMMIT_REF_NAME
    policy: pull
    paths:
      - node_modules
  script:
    - yarn test
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
